---
title: "DB_image_extract"
author: "Jake Eisaguirre"
date: "2022-09-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

# librarian downloads, if not already downloaded, and reads in needed packages

librarian::shelf(tidyverse, here, janitor, sf, lubridate, RPostgres, rstudioapi, jsonlite, DBI)
```


```{r}

tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv, 
                 dbname = Sys.getenv("dbname"),
                 host = Sys.getenv("host"), 
                 port = Sys.getenv("port"),
                 user = Sys.getenv("user"), 
                 password = Sys.getenv("password"))
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })

dbExecute(connection, "set search_path to serdp")

```

```{r}

# Query string - edit this to suit your needs
# Important thing here is that we're getting Postgres to base64 encode
#   the image data (converting it from binary to text)
thisQ = "SELECT encode(category_image, 'base64') AS image from test_img;"

# Execute the SELECT query and fetch the results
resultSet = dbSendQuery(connection, thisQ)
resultData <- dbFetch(resultSet, n=-1)
dbClearResult(resultSet)

# Get the image data as text
imageData <- resultData$image

# Decode from base64 back to binary
imageDataDecoded <- jsonlite::base64_dec(imageData)

# Create a file connection and write the binary data to disk using mode "wb".
write.filename = file(here("thermal.jpg"), "wb")
writeBin(imageDataDecoded, write.filename)
close(write.filename)
```

